### ISSUE TITLE
Please support collapse_key in GCM

### ISSUE THREAD

**Issue by koko1000ban** [lloydmeta/push_to_devices#8]
it needs when devices is sleeping

**Comment by lloydmeta** [comment]
In https://github.com/lloydmeta/push_to_devices/pull/7/files, we can put both data and options (collapse_key goes into option) inside android_specific_fields when POSTing a notification. The android_version used to support this, but with the new default options for android, this needs to be redone, perhaps with default_andoid_data and default_android_options. 

The documentation was unfortunately out of date and that's probably why android notifications didn't have any text...

**Comment by koko1000ban** [comment]
i don't know this "with the new default options for android, this needs to be redone". 
Thank you for letting me know :)
